# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: linkedsemi
      url-base: https://github.com/linkedsemi

  projects:
    - name: zephyr
      remote: linkedsemi
      revision: zephyr-v3.5.0-linkedsemi
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - segger     # required by the flashing
          - tinycrypt  # required by the BLE crypto
          - hal_linkedsemi     # required by the custom_plank board